version: '3.8'

services:
  api:
    build: .
    container_name: nexusolve-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      # LangSmith Tracing (Observability)
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=nexusolve-rag

  ui:
    build: .
    container_name: nexusolve-ui
    command: streamlit run ui.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}